# Generated by Django 3.2.25 on 2024-05-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
