# Generated by Django 3.2.25 on 2024-05-16 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_default_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_name',
            new_name='default_full_name',
        ),
    ]
