# Generated by Django 3.2.25 on 2024-05-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='heard_about_us',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
